name: auto README

# workflow will trigger every 6 hrs, and on push to master
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - run: npm ci
      - run: npm run build
      - name: add .env
        run: |
          touch .env
          echo GHUB_PERSONAL_ACCESS_TOKEN=${{ secrets.GHUB_PERSONAL_ACCESS_TOKEN }} >> .env
          echo LANGUAGE_COUNT=${{ secrets.LANGUAGE_COUNT }} >> .env
          echo DECIMAL_PRECISION=${{ secrets.DECIMAL_PRECISION }} >> .env
      - run: ls
      - name: Generate README file and assets by running the script
        run: npm start
        env:
          CI: true
          GHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GHUB_PERSONAL_ACCESS_TOKEN }}
          LANGUAGE_COUNT: ${{ secrets.LANGUAGE_COUNT }}
          DECIMAL_PRECISION: ${{ secrets.DECIMAL_PRECISION }}
      - name: Commit and Push new README.md to the repository
        uses: SD170/readme-auto-language-poll@master
        env:
          CI: true
          GHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GHUB_PERSONAL_ACCESS_TOKEN }}
          LANGUAGE_COUNT: ${{ secrets.LANGUAGE_COUNT }}
          DECIMAL_PRECISION: ${{ secrets.DECIMAL_PRECISION }}
